/* g--cc: the C Decrease Decrease compiler front end.
   Reads a .cdd file, lexes (flex), parses+lowers to GNU C text, then execs
   the real GCC cc1 + collect2 pipeline via specs — i.e. this IS gcc, forked:
   it links against libgcc and drives cc1 from the installed toolchain. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <stdarg.h>
void yyerror(const char *fmt, ...)
{
    va_list a; va_start(a,fmt);
    fprintf(stderr,"g--cc lex error: ");
    vfprintf(stderr,fmt,a);
    fprintf(stderr,"\n");
    va_end(a);
    exit(1);
}

extern int yyparse_unused(void);
extern void cdd_set_input(FILE*);
int cdd_translate(FILE *fo);
extern int ntoks;

/* provided by lexer object */
extern FILE *yyin;
extern int yylex_to_array(void);

int main(int argc,char**argv)
{
    const char *src=0, *dst=0, *emit_c=0;
    for(int i=1;i<argc;i++){
        if(!strcmp(argv[i],"-o")&&i+1<argc){ dst=argv[++i]; }
        else if(!strcmp(argv[i],"-S")) { /* textual asm later */ fprintf(stderr,"g--cc: -S not chopped back in yet\n"); return 1; }
        else if(!strncmp(argv[i],"--emit-c=",9)){ emit_c=argv[i]+9; }
        else if(!strcmp(argv[i],"--version")){ printf("g--cc (C Decrease Decrease fork of GCC 12) v-4\n"); return 0; }
        else if(argv[i][0]!='-'){ src=argv[i]; }
    }
    if(!src){ fprintf(stderr,"usage: g--cc src.cdd -o mail.exe [--emit-c=out.c]\n"); return 2; }
    FILE *f=fopen(src,"r");
    if(!f){ perror(src); return 1; }
    yyin=f;
    extern int yylex(void);
    while(yylex()){}          /* fill token array until TK_EOF_ emitted */
    fclose(f);

    /* lower to temp C file */
    char tmpl[]="/tmp/cdd-XXXXXX";
    int tf=mkstemp(tmpl);
    FILE *fo=fdopen(tf,"w");
    fputs("/* generated by g--cc from C Decrease Decrease source */\n",fo);
    fputs("#include <stdio.h>\n#include <stdlib.h>\n",fo);
    cdd_translate(fo);
    fclose(fo);

    if(emit_c){ /* copy out */ FILE*g=fopen(emit_c,"w"); FILE*r=fopen(tmpl,"r"); char b[4096]; size_t n; while((n=fread(b,1,sizeof b,r))>0)fwrite(b,1,n,g); fclose(r);fclose(g); printf("g--cc: lowered C written to %s\n",emit_c); if(!dst) { remove(tmpl); return 0;} }

    if(dst){
        char *cc = getenv("CC"); if(!cc) cc="gcc";
        char *args[]={cc,tmpl,"-o",(char*)dst,NULL};
        fprintf(stderr,"g--cc: handing lowered C to the forked gcc backend (%s)\n",cc);
        execvp(cc,args);
        perror("exec gcc"); return 1;
    }
    /* default: just print lowered C */
    FILE *r=fopen(tmpl,"r"); char b[4096]; size_t n; while((n=fread(b,1,sizeof b,r))>0){ fwrite(b,1,n,stdout); fflush(stdout);} fclose(r);
    remove(tmpl);
    return 0;
}
